site_name: DDB

repo_url: https://gitlab.eds.aphp.fr/ThomasPJ/ddb
repo_name: DDB

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  #logo: _static/logo.svg
  #favicon: assets/logo/scikit_eds.svg

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    - navigation.top
    - content.code.annotate

nav:
  - index.md
  - carte.md
  - toilettes.md
  - masque_et_plume.md
  - theoffice.md
extra_css:
  - _static/extra.css
  - _static/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - _static/extra.js
  - _static/termynal/termynal.js

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - codehilite
  - tables
